- 
  name: "Create network interfaces definition"
  template: 
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- 
  name: "Create wpa supplicant configuration file"
  template: 
    src: wpa_supplicant.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0644
